### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by Drumber**
Added missing strings and updated some translations.

### CODE REVIEW

**Comment by Moutony** [comment]
Line 152: I'm not sure that a text inside a CDATA is editable.

**Comment by Drumber** [comment]
Hi, I see no reason why CDATA tags shouldn't be translated. Also, I have tested everything for functionality and it works:
grafik

**Comment by Moutony** [comment]
I tried to set my phone in German.
The widget datei in my homescreen is in German.
But the app is not.

**Comment by Moutony** [comment]
I tried to set my phone in German. The widget datei in my homescreen is in German. But the app is still in English.
Please, can you test if the button AGB works? If yes, I will change the French strings.xml like you did.

**Comment by Drumber** [comment]
Translated Privacy button works fine.
output

**Pull request merged**
