### PR TITLE
Update stings.xml (values-fr) - May 11, 2020 version

### PR DESCRIPTION
**Pull request by Moutony**
I added new French translations and I fixed some old ones.
I will close the former (outdated) translation update that I made yesterday.
Please consider my proposing and update the file soon :)

### CODE REVIEW

**Comment by tommasoberlose** [comment]
Hey, I've just pushed to the repository a new version of the app with a brand new strings.xml file. I updated a few strings and reorganized the file to make it more readable.

I'm looking forward to inserting the missing translations in the next update so could you please update this pull request with the new changes? Thanks in advance!

**Comment by Moutony** [comment]
Where is the values-fr folder? I can't find the xml file.

**Comment by Moutony** [comment]
Ok I will overwrite the english values file. Thanks for reorganizing.

**Comment by tommasoberlose** [comment]
I've just updated the master branch, please pull the new updates before pushing a new version of this PR. Thanks!

**Comment by Moutony** [comment]
I close this pull, I published a new pull.

**Pull request closed without merging**
