### PR TITLE
Create Indonesian translation

### PR DESCRIPTION
**Pull request by zmni**
Can you explain the context of each of these strings?

```
<string name="h_code">h</string>
<string name="min_code">" min"</string>
<string name="in_code">in</string>
<string name="hs_code">h</string>
```

Thank you.

### CODE REVIEW

**Comment by Moutony** [comment]
It is the text that is displayed when the option "Remaining time until event" is Visible

**Comment by zmni** [comment]
Thank you.

**Comment by tommasoberlose** [comment]
Hey, I've just pushed to the repository a new version of the app with a brand new strings.xml file. I updated a few strings and reorganized the file to make it more readable.

I'm looking forward to inserting the missing translations in the next update so could you please update this pull request with the new changes? Thanks in advance!

**Comment by zmni** [comment]
Translation updated. And what should I do about this failed checks?

**Comment by tommasoberlose** [comment]
> Translation updated. And what should I do about this failed checks?

Thank you, I'll take care of the failed checks.

**Pull request merged**
